{{- if .Values.ingress.cert -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 1726142454@qq.com
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}


