apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arkid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "arkid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "arkid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
      - image: busybox
        command:
        - sh
        - -c
        - echo 65535 > /proc/sys/net/core/somaxconn
        imagePullPolicy: Always
        name: setsysctl
        securityContext:
          privileged: true
      nodeName: cn-shenzhen.172.18.63.65
      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.image.webServer.name }}"
          image: "{{ .Values.image.webServer.repository }}:{{ .Values.image.webServer.tag }}"
          imagePullPolicy: {{ .Values.image.webServer.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping/
              port: http
          readinessProbe:
            httpGet:
              path: /ping/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: "settings-local"
              mountPath: "/var/oneid/settings_local.py"
              subPath: "settings_local.py"
            - name: arkid-data
              mountPath: /var/oneid/upload
              subPath: be/upload
            # @TODO: mount plugins
            # - name: arkid-data
            #   mountPath: /var/oneid/plugins
            #   subPath: be/plugins

        - name: "{{ .Chart.Name }}-{{ .Values.image.webServerBroker.name }}"
          image: "{{ .Values.image.webServerBroker.repository }}:{{ .Values.image.webServerBroker.tag }}"
          imagePullPolicy: {{ .Values.image.webServerBroker.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args: ["broker", "-t", "http://localhost", "-p", "8080"]
      volumes:
        - name: settings-local
          configMap:
            name: {{ template "arkid.fullname" . }}
        - name: arkid-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}

      {{if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
