apiVersion: v1
kind: Service
metadata:
  name: {{ include "arkid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    helm.sh/chart: {{ include "arkid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webServer.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - name: broker
      port: {{ .Values.service.webServerBroker.port }}
      targetPort: 8080
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "arkid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
